/**
 * @author Saki
 * @date 2019-03-28 20:44:32
 * @Last Modified by: Saki
 * @Last Modified time: 2019-03-29 11:11:19
 * 
 * Main, generated by vue ui
 */
import Vue from 'vue';
import App from './App.vue';

// this instance handles buttons and slider events
export const eventBus = new Vue();

Vue.config.productionTip = false;

new Vue({
  render: h => h(App),
}).$mount('#app')

// eof
