/**
 * @author Saki
 * @date 2019-03-28 12:58:54
 * @Last Modified by: Saki
 * @Last Modified time: 2019-03-28 19:47:53
 * 
 * The application starts here 
 * generated by vue ui
 */
import Vue from 'vue';
import App from './App.vue';

Vue.config.productionTip = false;

new Vue({
    render: h => h(App)
}).$mount('#app')

// eof
